version: '3.9'
services:
  server:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${PWD}/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "${PWD}/server/:/etc/nginx/conf.d/:ro"
      - "certbot-www:/var/www/certbot/:ro"
      - "certbot-conf:/etc/nginx/ssl/:ro"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  certbot:
    image: certbot/certbot:latest
    volumes:
      - "certbot-www:/var/www/certbot/:rw"
      - "certbot-conf:/etc/letsencrypt/:rw"
    depends_on:
      - server
volumes:
  certbot-conf:
  certbot-www:
